### ISSUE TITLE
storages/db/scripts/populate.py:112 TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by sneak** [steemit/sbds#23]
```

Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:  [1/7]   Confirm database connectivity...
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:  success connected to sqlite:////tmp/sqlite.db and found 19 tables
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:  [2/7]   Killing active db threads...
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:  {"levelname": "INFO", "asctime": "2017-02-18T00:59:17.1487379557GMT", "module": "utils", "funcName": "isolated_engine", "lineno": 269, "msecs": 584.0926170349121, "message": "unsupported function for sqlite database", "process": 1879, "processName": "MainProcess", "threadName": "MainThread"}
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:  {"levelname": "INFO", "asctime": "2017-02-18T00:59:17.1487379557GMT", "module": "utils", "funcName": "isolated_engine", "lineno": 269, "msecs": 584.0926170349121, "message": "unsupported function for sqlite database", "process": 1879, "processName": "MainProcess", "threadName": "MainThread"}
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:  {"levelname": "INFO", "asctime": "2017-02-18T00:59:17.1487379557GMT", "module": "utils", "funcName": "isolated_engine", "lineno": 269, "msecs": 585.0942134857178, "message": "'NoneType' object is not iterable", "process": 1879, "processName": "MainProcess", "threadName": "MainThread"}
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:  {"levelname": "INFO", "asctime": "2017-02-18T00:59:17.1487379557GMT", "module": "utils", "funcName": "isolated_engine", "lineno": 269, "msecs": 585.0942134857178, "message": "'NoneType' object is not iterable", "process": 1879, "processName": "MainProcess", "threadName": "MainThread"}
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:  Traceback (most recent call last):
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:    File "/usr/local/bin/populate", line 9, in <module>
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:      load_entry_point('sbds==0.1', 'console_scripts', 'populate')()
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:    File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 722, in __call__
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:      return self.main(*args, **kwargs)
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:    File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 697, in main
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:      rv = self.invoke(ctx)
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:    File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 895, in invoke
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:      return ctx.invoke(self.callback, **ctx.params)
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:    File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 535, in invoke
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:      return callback(*args, **kwargs)
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:    File "/usr/local/lib/python3.5/dist-packages/sbds/storages/db/scripts/populate.py", line 74, in populate
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:      max_threads)
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:    File "/usr/local/lib/python3.5/dist-packages/sbds/storages/db/scripts/populate.py", line 112, in _populate
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:      db_user_name)
Feb 18 00:59:17 648be2a35aed ecs-awseb-steemit-dev-sbds-001-jezgax5sr2-1-steemit-sbds-b898cad:  TypeError: 'NoneType' object is not iterable
````

@jredbeard this should be using mysql not sqlite, is it not picking up its database url?

**Comment by jredbeard** [comment]
env vars are added back - i had to re-build the environment earlier when switching to the single container and didn't get them added back in right away
