### ISSUE TITLE
Quirky SQLAlchemy connection management causing to MySQL Connection Errrors

### ISSUE THREAD

**Issue by john-g-g** [steemit/sbds#39]
View details in Rollbar: [https://rollbar.com/Steemit/sbds/items/29/](https://rollbar.com/Steemit/sbds/items/29/)

```
Traceback (most recent call last):
  File "/Users/muyloco/Dev/steem/sbds/sbds/storages/db/utils.py", line 124, in session_scope
    session.commit()
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 874, in commit
    self.transaction.commit()
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 461, in commit
    self._prepare_impl()
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 441, in _prepare_impl
    self.session.flush()
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2139, in flush
    self._flush(objects)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2259, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 2223, in _flush
    flush_context.execute()
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 389, in execute
    rec.execute(self)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/orm/unitofwork.py", line 548, in execute
    uow
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 156, in save_obj
    base_mapper, states, uowtransaction
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 279, in _organize_states_for_save
    states):
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/orm/persistence.py", line 1105, in _connections_for_states
    connection = uowtransaction.transaction.connection(base_mapper)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 294, in connection
    return self._connection_for_bind(bind, execution_options)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 392, in _connection_for_bind
    conn = self._parent._connection_for_bind(bind, execution_options)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 392, in _connection_for_bind
    conn = self._parent._connection_for_bind(bind, execution_options)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/orm/session.py", line 403, in _connection_for_bind
    conn = bind.contextual_connect()
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2103, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2142, in _wrap_pool_connect
    e, dialect, self)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 1456, in _handle_dbapi_exception_noconnection
    exc_info
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2138, in _wrap_pool_connect
    return fn()
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/pool.py", line 766, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/pool.py", line 521, in checkout
    rec.checkin()
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 187, in reraise
    raise value
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/pool.py", line 518, in checkout
    dbapi_connection = rec.get_connection()
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/pool.py", line 607, in get_connection
    self.__connect()
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/MySQLdb/__init__.py", line 86, in Connect
    return Connection(*args, **kwargs)
  File "/Users/muyloco/Dev/Envs/sbds/lib/python3.5/site-packages/MySQLdb/connections.py", line 204, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
OperationalError: (_mysql_exceptions.OperationalError) (2003, "Can't connect to MySQL server on 'sbds-dev-1.c5fwsnh29c0p.us-east-1.rds.amazonaws.com' (60)")
```

**Comment by Netherdrake** [comment]
I am getting a similar error:
```
2017-05-30T14:14:14.054758090Z [1/6]   Confirm database connectivity...
2017-05-30T14:14:14.353878401Z success connected to mysql://root:***@sbds-mysql:3306/sbds?charset=utf8mb4 and found 36 tables
2017-05-30T14:14:14.354029376Z [2/6]   Initialising db if required...
2017-05-30T14:14:14.527683687Z [3/6]   Finding highest blockchain block...
2017-05-30T14:14:14.529480792Z [4/6]   Finding blocks missing from db...
2017-05-30T14:14:14.576154458Z Finding missing block_nums
2017-05-30T14:15:02.837913176Z success found 9164649 missing blocks
2017-05-30T14:15:02.870166845Z [5/6]   Adding missing blocks to db, this may take a while...
2017-05-30T14:15:40.352021300Z Exception during reset or similar
2017-05-30T14:15:40.352054926Z Traceback (most recent call last):
2017-05-30T14:15:40.352062025Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
2017-05-30T14:15:40.352067058Z     fairy._reset(pool)
2017-05-30T14:15:40.352071277Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 829, in _reset
2017-05-30T14:15:40.352075876Z     pool._dialect.do_rollback(self)
2017-05-30T14:15:40.352080220Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/dialects/mysql/base.py", line 1598, in do_rollback
2017-05-30T14:15:40.352085002Z     dbapi_connection.rollback()
2017-05-30T14:15:40.352089142Z _mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')
2017-05-30T14:15:40.369251358Z Exception during reset or similar
2017-05-30T14:15:40.369286835Z Traceback (most recent call last):
2017-05-30T14:15:40.369294446Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
2017-05-30T14:15:40.369299602Z     fairy._reset(pool)
2017-05-30T14:15:40.369303925Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 829, in _reset
2017-05-30T14:15:40.369308605Z     pool._dialect.do_rollback(self)
2017-05-30T14:15:40.369313007Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/dialects/mysql/base.py", line 1598, in do_rollback
2017-05-30T14:15:40.369317335Z     dbapi_connection.rollback()
2017-05-30T14:15:40.369321439Z _mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')
2017-05-30T14:15:40.375026902Z Exception during reset or similar
2017-05-30T14:15:40.375050106Z Traceback (most recent call last):
2017-05-30T14:15:40.375055764Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
2017-05-30T14:15:40.375060222Z     fairy._reset(pool)
2017-05-30T14:15:40.375064708Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 829, in _reset
2017-05-30T14:15:40.375068656Z     pool._dialect.do_rollback(self)
2017-05-30T14:15:40.375072081Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/dialects/mysql/base.py", line 1598, in do_rollback
2017-05-30T14:15:40.375082827Z     dbapi_connection.rollback()
2017-05-30T14:15:40.375086834Z _mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')
2017-05-30T14:15:40.380878912Z Exception during reset or similar
2017-05-30T14:15:40.380904252Z Traceback (most recent call last):
2017-05-30T14:15:40.380909751Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
2017-05-30T14:15:40.380914188Z     fairy._reset(pool)
2017-05-30T14:15:40.380919314Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 829, in _reset
2017-05-30T14:15:40.380923697Z     pool._dialect.do_rollback(self)
2017-05-30T14:15:40.380927557Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/dialects/mysql/base.py", line 1598, in do_rollback
2017-05-30T14:15:40.380933116Z     dbapi_connection.rollback()
2017-05-30T14:15:40.380936954Z _mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')
2017-05-30T14:15:40.387315499Z Exception during reset or similar
2017-05-30T14:15:40.387340654Z Traceback (most recent call last):
2017-05-30T14:15:40.387345882Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
2017-05-30T14:15:40.387349754Z     fairy._reset(pool)
2017-05-30T14:15:40.387353477Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 829, in _reset
2017-05-30T14:15:40.387356839Z     pool._dialect.do_rollback(self)
2017-05-30T14:15:40.387360167Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/dialects/mysql/base.py", line 1598, in do_rollback
2017-05-30T14:15:40.387363738Z     dbapi_connection.rollback()
2017-05-30T14:15:40.387366768Z _mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')
2017-05-30T14:15:40.387502639Z Exception during reset or similar
2017-05-30T14:15:40.387516785Z Traceback (most recent call last):
2017-05-30T14:15:40.387521502Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
2017-05-30T14:15:40.387525419Z     fairy._reset(pool)
2017-05-30T14:15:40.387529120Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 829, in _reset
2017-05-30T14:15:40.387532624Z     pool._dialect.do_rollback(self)
2017-05-30T14:15:40.387535711Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/dialects/mysql/base.py", line 1598, in do_rollback
2017-05-30T14:15:40.387539544Z     dbapi_connection.rollback()
2017-05-30T14:15:40.387542898Z _mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')
2017-05-30T14:15:40.387550464Z Exception during reset or similar
2017-05-30T14:15:40.387554100Z Traceback (most recent call last):
2017-05-30T14:15:40.387557371Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
2017-05-30T14:15:40.387566752Z     fairy._reset(pool)
2017-05-30T14:15:40.387569764Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 829, in _reset
2017-05-30T14:15:40.387572711Z     pool._dialect.do_rollback(self)
2017-05-30T14:15:40.387576962Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/dialects/mysql/base.py", line 1598, in do_rollback
2017-05-30T14:15:40.387580592Z     dbapi_connection.rollback()
2017-05-30T14:15:40.387583774Z _mysql_exceptions.OperationalError: (2006, 'MySQL server has gone away')
2017-05-30T14:15:40.394282772Z Exception during reset or similar
2017-05-30T14:15:40.394310366Z Traceback (most recent call last):
2017-05-30T14:15:40.394315433Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 687, in _finalize_fairy
2017-05-30T14:15:40.394319095Z     fairy._reset(pool)
2017-05-30T14:15:40.394322779Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 829, in _reset
2017-05-30T14:15:40.394325988Z     pool._dialect.do_rollback(self)
2017-05-30T14:15:40.394328868Z   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/dialects/mysql/base.py", line 1598, in do_rollback
2017-05-30T14:15:40.394331898Z     dbapi_connection.rollback()
2017-05-30T14:15:40.394334930Z _mysql_exceptions.OperationalError: (2013, 'Lost connection to MySQL server during query')
```
